# distutils: language = c++

from libcythonplus.dict cimport cypdict
from stdlib.string cimport string as Str


# cdef const char* c_wrap_get_type(MediaTypes mt, Str path) nogil:
#     return mt.get_type(path)


cdef const char* extension(Str filename) nogil:
    cdef size_t pos = filename.find_last_of(".")
    return filename.substr(pos + 1).c_str()


cdef Sdict default_types() nogil:
    cdef Sdict d

    d = Sdict()
    d[Str(".3gp").c_str()] = Str("video/3gpp").c_str()
    d[Str(".3gp").c_str()] = Str("video/3gpp").c_str()
    d[Str(".3gpp").c_str()] = Str("video/3gpp").c_str()
    d[Str(".7z").c_str()] = Str("application/x-7z-compressed").c_str()
    d[Str(".ai").c_str()] = Str("application/postscript").c_str()
    d[Str(".asf").c_str()] = Str("video/x-ms-asf").c_str()
    d[Str(".asx").c_str()] = Str("video/x-ms-asf").c_str()
    d[Str(".atom").c_str()] = Str("application/atom+xml").c_str()
    d[Str(".avi").c_str()] = Str("video/x-msvideo").c_str()
    d[Str(".bmp").c_str()] = Str("image/x-ms-bmp").c_str()
    d[Str(".cco").c_str()] = Str("application/x-cocoa").c_str()
    d[Str(".crt").c_str()] = Str("application/x-x509-ca-cert").c_str()
    d[Str(".css").c_str()] = Str("text/css").c_str()
    d[Str(".der").c_str()] = Str("application/x-x509-ca-cert").c_str()
    d[Str(".doc").c_str()] = Str("application/msword").c_str()
    d[Str(".docx").c_str()] = Str("application/vnd.openxmlformats-officedocument.wordprocessingml.document").c_str()
    d[Str(".ear").c_str()] = Str("application/java-archive").c_str()
    d[Str(".eot").c_str()] = Str("application/vnd.ms-fontobject").c_str()
    d[Str(".eps").c_str()] = Str("application/postscript").c_str()
    d[Str(".flv").c_str()] = Str("video/x-flv").c_str()
    d[Str(".gif").c_str()] = Str("image/gif").c_str()
    d[Str(".hqx").c_str()] = Str("application/mac-binhex40").c_str()
    d[Str(".htc").c_str()] = Str("text/x-component").c_str()
    d[Str(".htm").c_str()] = Str("text/html").c_str()
    d[Str(".html").c_str()] = Str("text/html").c_str()
    d[Str(".ico").c_str()] = Str("image/x-icon").c_str()
    d[Str(".jad").c_str()] = Str("text/vnd.sun.j2me.app-descriptor").c_str()
    d[Str(".jar").c_str()] = Str("application/java-archive").c_str()
    d[Str(".jardiff").c_str()] = Str("application/x-java-archive-diff").c_str()
    d[Str(".jng").c_str()] = Str("image/x-jng").c_str()
    d[Str(".jnlp").c_str()] = Str("application/x-java-jnlp-file").c_str()
    d[Str(".jpeg").c_str()] = Str("image/jpeg").c_str()
    d[Str(".jpg").c_str()] = Str("image/jpeg").c_str()
    d[Str(".js").c_str()] = Str("text/javascript").c_str()
    d[Str(".json").c_str()] = Str("application/json").c_str()
    d[Str(".kar").c_str()] = Str("audio/midi").c_str()
    d[Str(".kml").c_str()] = Str("application/vnd.google-earth.kml+xml").c_str()
    d[Str(".kmz").c_str()] = Str("application/vnd.google-earth.kmz").c_str()
    d[Str(".m3u8").c_str()] = Str("application/vnd.apple.mpegurl").c_str()
    d[Str(".m4a").c_str()] = Str("audio/x-m4a").c_str()
    d[Str(".m4v").c_str()] = Str("video/x-m4v").c_str()
    d[Str(".md").c_str()] = Str("text/markdown").c_str()
    d[Str(".mid").c_str()] = Str("audio/midi").c_str()
    d[Str(".midi").c_str()] = Str("audio/midi").c_str()
    d[Str(".mjs").c_str()] = Str("text/javascript").c_str()
    d[Str(".mml").c_str()] = Str("text/mathml").c_str()
    d[Str(".mng").c_str()] = Str("video/x-mng").c_str()
    d[Str(".mov").c_str()] = Str("video/quicktime").c_str()
    d[Str(".mp3").c_str()] = Str("audio/mpeg").c_str()
    d[Str(".mp4").c_str()] = Str("video/mp4").c_str()
    d[Str(".mpeg").c_str()] = Str("video/mpeg").c_str()
    d[Str(".mpg").c_str()] = Str("video/mpeg").c_str()
    d[Str(".ogg").c_str()] = Str("audio/ogg").c_str()
    d[Str(".pdb").c_str()] = Str("application/x-pilot").c_str()
    d[Str(".pdf").c_str()] = Str("application/pdf").c_str()
    d[Str(".pem").c_str()] = Str("application/x-x509-ca-cert").c_str()
    d[Str(".pl").c_str()] = Str("application/x-perl").c_str()
    d[Str(".pm").c_str()] = Str("application/x-perl").c_str()
    d[Str(".png").c_str()] = Str("image/png").c_str()
    d[Str(".ppt").c_str()] = Str("application/vnd.ms-powerpoint").c_str()
    d[Str(".pptx").c_str()] = Str("application/vnd.openxmlformats-officedocument.presentationml.presentation").c_str()
    d[Str(".prc").c_str()] = Str("application/x-pilot").c_str()
    d[Str(".ps").c_str()] = Str("application/postscript").c_str()
    d[Str(".ra").c_str()] = Str("audio/x-realaudio").c_str()
    d[Str(".rar").c_str()] = Str("application/x-rar-compressed").c_str()
    d[Str(".rpm").c_str()] = Str("application/x-redhat-package-manager").c_str()
    d[Str(".rss").c_str()] = Str("application/rss+xml").c_str()
    d[Str(".rtf").c_str()] = Str("application/rtf").c_str()
    d[Str(".run").c_str()] = Str("application/x-makeself").c_str()
    d[Str(".sea").c_str()] = Str("application/x-sea").c_str()
    d[Str(".shtml").c_str()] = Str("text/html").c_str()
    d[Str(".sit").c_str()] = Str("application/x-stuffit").c_str()
    d[Str(".svg").c_str()] = Str("image/svg+xml").c_str()
    d[Str(".svgz").c_str()] = Str("image/svg+xml").c_str()
    d[Str(".swf").c_str()] = Str("application/x-shockwave-flash").c_str()
    d[Str(".tcl").c_str()] = Str("application/x-tcl").c_str()
    d[Str(".tif").c_str()] = Str("image/tiff").c_str()
    d[Str(".tiff").c_str()] = Str("image/tiff").c_str()
    d[Str(".tk").c_str()] = Str("application/x-tcl").c_str()
    d[Str(".ts").c_str()] = Str("video/mp2t").c_str()
    d[Str(".txt").c_str()] = Str("text/plain").c_str()
    d[Str(".wasm").c_str()] = Str("application/wasm").c_str()
    d[Str(".war").c_str()] = Str("application/java-archive").c_str()
    d[Str(".wbmp").c_str()] = Str("image/vnd.wap.wbmp").c_str()
    d[Str(".webm").c_str()] = Str("video/webm").c_str()
    d[Str(".webp").c_str()] = Str("image/webp").c_str()
    d[Str(".wml").c_str()] = Str("text/vnd.wap.wml").c_str()
    d[Str(".wmlc").c_str()] = Str("application/vnd.wap.wmlc").c_str()
    d[Str(".wmv").c_str()] = Str("video/x-ms-wmv").c_str()
    d[Str(".woff").c_str()] = Str("application/font-woff").c_str()
    d[Str(".woff2").c_str()] = Str("font/woff2").c_str()
    d[Str(".xhtml").c_str()] = Str("application/xhtml+xml").c_str()
    d[Str(".xls").c_str()] = Str("application/vnd.ms-excel").c_str()
    d[Str(".xlsx").c_str()] = Str("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").c_str()
    d[Str(".xml").c_str()] = Str("text/xml").c_str()
    d[Str(".xpi").c_str()] = Str("application/x-xpinstall").c_str()
    d[Str(".xspf").c_str()] = Str("application/xspf+xml").c_str()
    d[Str(".zip").c_str()] = Str("application/zip").c_str()
    d[Str("apple-app-site-association").c_str()] = Str("application/pkc7-mime").c_str()
    d[Str("crossdomain.xml").c_str()] = Str("text/x-cross-domain-policy").c_str()

    d[Str(".3GP").c_str()] = Str("video/3gpp").c_str()
    d[Str(".3GP").c_str()] = Str("video/3gpp").c_str()
    d[Str(".3GPP").c_str()] = Str("video/3gpp").c_str()
    d[Str(".7Z").c_str()] = Str("application/x-7z-compressed").c_str()
    d[Str(".AI").c_str()] = Str("application/postscript").c_str()
    d[Str(".ASF").c_str()] = Str("video/x-ms-asf").c_str()
    d[Str(".ASX").c_str()] = Str("video/x-ms-asf").c_str()
    d[Str(".ATOM").c_str()] = Str("application/atom+xml").c_str()
    d[Str(".AVI").c_str()] = Str("video/x-msvideo").c_str()
    d[Str(".BMP").c_str()] = Str("image/x-ms-bmp").c_str()
    d[Str(".CCO").c_str()] = Str("application/x-cocoa").c_str()
    d[Str(".CRT").c_str()] = Str("application/x-x509-ca-cert").c_str()
    d[Str(".CSS").c_str()] = Str("text/css").c_str()
    d[Str(".DER").c_str()] = Str("application/x-x509-ca-cert").c_str()
    d[Str(".DOC").c_str()] = Str("application/msword").c_str()
    d[Str(".DOCX").c_str()] = Str("application/vnd.openxmlformats-officedocument.wordprocessingml.document").c_str()
    d[Str(".EAR").c_str()] = Str("application/java-archive").c_str()
    d[Str(".EOT").c_str()] = Str("application/vnd.ms-fontobject").c_str()
    d[Str(".EPS").c_str()] = Str("application/postscript").c_str()
    d[Str(".FLV").c_str()] = Str("video/x-flv").c_str()
    d[Str(".GIF").c_str()] = Str("image/gif").c_str()
    d[Str(".HQX").c_str()] = Str("application/mac-binhex40").c_str()
    d[Str(".HTC").c_str()] = Str("text/x-component").c_str()
    d[Str(".HTM").c_str()] = Str("text/html").c_str()
    d[Str(".HTML").c_str()] = Str("text/html").c_str()
    d[Str(".ICO").c_str()] = Str("image/x-icon").c_str()
    d[Str(".JAD").c_str()] = Str("text/vnd.sun.j2me.app-descriptor").c_str()
    d[Str(".JAR").c_str()] = Str("application/java-archive").c_str()
    d[Str(".JARDIff").c_str()] = Str("application/x-java-archive-diff").c_str()
    d[Str(".JNG").c_str()] = Str("image/x-jng").c_str()
    d[Str(".JNLP").c_str()] = Str("application/x-java-jnlp-file").c_str()
    d[Str(".JPEG").c_str()] = Str("image/jpeg").c_str()
    d[Str(".JPG").c_str()] = Str("image/jpeg").c_str()
    d[Str(".JS").c_str()] = Str("text/javascript").c_str()
    d[Str(".JSON").c_str()] = Str("application/json").c_str()
    d[Str(".KAR").c_str()] = Str("audio/midi").c_str()
    d[Str(".KML").c_str()] = Str("application/vnd.google-earth.kml+xml").c_str()
    d[Str(".KMZ").c_str()] = Str("application/vnd.google-earth.kmz").c_str()
    d[Str(".M3U8").c_str()] = Str("application/vnd.apple.mpegurl").c_str()
    d[Str(".M4A").c_str()] = Str("audio/x-m4a").c_str()
    d[Str(".M4V").c_str()] = Str("video/x-m4v").c_str()
    d[Str(".MD").c_str()] = Str("text/markdown").c_str()
    d[Str(".MID").c_str()] = Str("audio/midi").c_str()
    d[Str(".MIDI").c_str()] = Str("audio/midi").c_str()
    d[Str(".MJS").c_str()] = Str("text/javascript").c_str()
    d[Str(".MML").c_str()] = Str("text/mathml").c_str()
    d[Str(".MNG").c_str()] = Str("video/x-mng").c_str()
    d[Str(".MOV").c_str()] = Str("video/quicktime").c_str()
    d[Str(".MP3").c_str()] = Str("audio/mpeg").c_str()
    d[Str(".MP4").c_str()] = Str("video/mp4").c_str()
    d[Str(".MPEG").c_str()] = Str("video/mpeg").c_str()
    d[Str(".MPG").c_str()] = Str("video/mpeg").c_str()
    d[Str(".OGG").c_str()] = Str("audio/ogg").c_str()
    d[Str(".PDB").c_str()] = Str("application/x-pilot").c_str()
    d[Str(".PDF").c_str()] = Str("application/pdf").c_str()
    d[Str(".PEM").c_str()] = Str("application/x-x509-ca-cert").c_str()
    d[Str(".PL").c_str()] = Str("application/x-perl").c_str()
    d[Str(".PM").c_str()] = Str("application/x-perl").c_str()
    d[Str(".PNG").c_str()] = Str("image/png").c_str()
    d[Str(".PPT").c_str()] = Str("application/vnd.ms-powerpoint").c_str()
    d[Str(".PPTX").c_str()] = Str("application/vnd.openxmlformats-officedocument.presentationml.presentation").c_str()
    d[Str(".PRC").c_str()] = Str("application/x-pilot").c_str()
    d[Str(".PS").c_str()] = Str("application/postscript").c_str()
    d[Str(".RA").c_str()] = Str("audio/x-realaudio").c_str()
    d[Str(".RAR").c_str()] = Str("application/x-rar-compressed").c_str()
    d[Str(".RPM").c_str()] = Str("application/x-redhat-package-manager").c_str()
    d[Str(".RSS").c_str()] = Str("application/rss+xml").c_str()
    d[Str(".RTF").c_str()] = Str("application/rtf").c_str()
    d[Str(".RUN").c_str()] = Str("application/x-makeself").c_str()
    d[Str(".SEA").c_str()] = Str("application/x-sea").c_str()
    d[Str(".SHTML").c_str()] = Str("text/html").c_str()
    d[Str(".SIT").c_str()] = Str("application/x-stuffit").c_str()
    d[Str(".SVG").c_str()] = Str("image/svg+xml").c_str()
    d[Str(".SVGZ").c_str()] = Str("image/svg+xml").c_str()
    d[Str(".SWF").c_str()] = Str("application/x-shockwave-flash").c_str()
    d[Str(".TCL").c_str()] = Str("application/x-tcl").c_str()
    d[Str(".TIF").c_str()] = Str("image/tiff").c_str()
    d[Str(".TIFF").c_str()] = Str("image/tiff").c_str()
    d[Str(".TK").c_str()] = Str("application/x-tcl").c_str()
    d[Str(".TS").c_str()] = Str("video/mp2t").c_str()
    d[Str(".TXT").c_str()] = Str("text/plain").c_str()
    d[Str(".WASM").c_str()] = Str("application/wasm").c_str()
    d[Str(".WAR").c_str()] = Str("application/java-archive").c_str()
    d[Str(".WBMP").c_str()] = Str("image/vnd.wap.wbmp").c_str()
    d[Str(".WEBM").c_str()] = Str("video/webm").c_str()
    d[Str(".WEBP").c_str()] = Str("image/webp").c_str()
    d[Str(".WML").c_str()] = Str("text/vnd.wap.wml").c_str()
    d[Str(".WMLC").c_str()] = Str("application/vnd.wap.wmlc").c_str()
    d[Str(".WMV").c_str()] = Str("video/x-ms-wmv").c_str()
    d[Str(".WOFF").c_str()] = Str("application/font-woff").c_str()
    d[Str(".WOFF2").c_str()] = Str("font/woff2").c_str()
    d[Str(".XHTML").c_str()] = Str("application/xhtml+xml").c_str()
    d[Str(".XLS").c_str()] = Str("application/vnd.ms-excel").c_str()
    d[Str(".XLSX").c_str()] = Str("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").c_str()
    d[Str(".XML").c_str()] = Str("text/xml").c_str()
    d[Str(".XPI").c_str()] = Str("application/x-xpinstall").c_str()
    d[Str(".XSPF").c_str()] = Str("application/xspf+xml").c_str()
    d[Str(".ZIP").c_str()] = Str("application/zip").c_str()
    d[Str("APPLE-APP-SITE-ASSOCIATION").c_str()] = Str("application/pkc7-mime").c_str()
    d[Str("CROSSDOMAIN.XML").c_str()] = Str("text/x-cross-domain-policy").c_str()

    return d


# def default_types():
#     """
#     We use our own set of default media types rather than the system-supplied
#     ones. This ensures consistent media type behaviour across varied
#     environments.  The defaults are based on those shipped with nginx, with
#     some custom additions.
#     """
#
#     return {
#         ".3gp": "video/3gpp",
#         ".3gpp": "video/3gpp",
#         ".7z": "application/x-7z-compressed",
#         ".ai": "application/postscript",
#         ".asf": "video/x-ms-asf",
#         ".asx": "video/x-ms-asf",
#         ".atom": "application/atom+xml",
#         ".avi": "video/x-msvideo",
#         ".bmp": "image/x-ms-bmp",
#         ".cco": "application/x-cocoa",
#         ".crt": "application/x-x509-ca-cert",
#         ".css": "text/css",
#         ".der": "application/x-x509-ca-cert",
#         ".doc": "application/msword",
#         ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
#         ".ear": "application/java-archive",
#         ".eot": "application/vnd.ms-fontobject",
#         ".eps": "application/postscript",
#         ".flv": "video/x-flv",
#         ".gif": "image/gif",
#         ".hqx": "application/mac-binhex40",
#         ".htc": "text/x-component",
#         ".htm": "text/html",
#         ".html": "text/html",
#         ".ico": "image/x-icon",
#         ".jad": "text/vnd.sun.j2me.app-descriptor",
#         ".jar": "application/java-archive",
#         ".jardiff": "application/x-java-archive-diff",
#         ".jng": "image/x-jng",
#         ".jnlp": "application/x-java-jnlp-file",
#         ".jpeg": "image/jpeg",
#         ".jpg": "image/jpeg",
#         ".js": "text/javascript",
#         ".json": "application/json",
#         ".kar": "audio/midi",
#         ".kml": "application/vnd.google-earth.kml+xml",
#         ".kmz": "application/vnd.google-earth.kmz",
#         ".m3u8": "application/vnd.apple.mpegurl",
#         ".m4a": "audio/x-m4a",
#         ".m4v": "video/x-m4v",
#         ".md": "text/markdown",
#         ".mid": "audio/midi",
#         ".midi": "audio/midi",
#         ".mjs": "text/javascript",
#         ".mml": "text/mathml",
#         ".mng": "video/x-mng",
#         ".mov": "video/quicktime",
#         ".mp3": "audio/mpeg",
#         ".mp4": "video/mp4",
#         ".mpeg": "video/mpeg",
#         ".mpg": "video/mpeg",
#         ".ogg": "audio/ogg",
#         ".pdb": "application/x-pilot",
#         ".pdf": "application/pdf",
#         ".pem": "application/x-x509-ca-cert",
#         ".pl": "application/x-perl",
#         ".pm": "application/x-perl",
#         ".png": "image/png",
#         ".ppt": "application/vnd.ms-powerpoint",
#         ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
#         ".prc": "application/x-pilot",
#         ".ps": "application/postscript",
#         ".ra": "audio/x-realaudio",
#         ".rar": "application/x-rar-compressed",
#         ".rpm": "application/x-redhat-package-manager",
#         ".rss": "application/rss+xml",
#         ".rtf": "application/rtf",
#         ".run": "application/x-makeself",
#         ".sea": "application/x-sea",
#         ".shtml": "text/html",
#         ".sit": "application/x-stuffit",
#         ".svg": "image/svg+xml",
#         ".svgz": "image/svg+xml",
#         ".swf": "application/x-shockwave-flash",
#         ".tcl": "application/x-tcl",
#         ".tif": "image/tiff",
#         ".tiff": "image/tiff",
#         ".tk": "application/x-tcl",
#         ".ts": "video/mp2t",
#         ".txt": "text/plain",
#         ".wasm": "application/wasm",
#         ".war": "application/java-archive",
#         ".wbmp": "image/vnd.wap.wbmp",
#         ".webm": "video/webm",
#         ".webp": "image/webp",
#         ".wml": "text/vnd.wap.wml",
#         ".wmlc": "application/vnd.wap.wmlc",
#         ".wmv": "video/x-ms-wmv",
#         ".woff": "application/font-woff",
#         ".woff2": "font/woff2",
#         ".xhtml": "application/xhtml+xml",
#         ".xls": "application/vnd.ms-excel",
#         ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
#         ".xml": "text/xml",
#         ".xpi": "application/x-xpinstall",
#         ".xspf": "application/xspf+xml",
#         ".zip": "application/zip",
#         "apple-app-site-association": "application/pkc7-mime",
#         # Adobe Products - see:
#         # https://www.adobe.com/devnet-docs/acrobatetk/tools/AppSec/xdomain.html#policy-file-host-basics
#         "crossdomain.xml": "text/x-cross-domain-policy",
#     }
