title = "N-queens, heuristic, sum of 5 runs, cython+ actors"
module = "n_queens_adv_heuristic_actor"
function = "main"
args = [250, 5]
args2 = [1000, 2]
title2 = "N-queens, heuristic, sum of 2 runs, cython+ actors"
