module = "n_queens_adv_heuristic_actor"
function = "main"
default_title = "N-queens, heuristic, sum of 2 runs, cython+ actors"
[[test]]
args = [100, 2]
[[test]]
args = [200, 2]
[[test]]
args = [500, 2]
[[test]]
args = [800, 2]
[[test]]
args = [1000, 2]
[[test]]
args = [1200, 2]
[[test]]
args = [1500, 2]
[[test]]
args = [1800, 2]
[[test]]
args = [2000, 2]
[[test]]
args = [2500, 2]
[[test]]
args = [3000, 2]
[[test]]
args = [3500, 2]
[[test]]
args = [4000, 2]
