# CythonPlus backend

[types]
int = "int"
float = "double"
str = "Str"
dict = "cypdict[Str, int]"
"Dict[int, int]" = "cypdict[int, int]"
"Dict[str, int]" = "cypdict[Str, int]"
list = "cyplist[int]"

[initializations]
int = "0"
double = "0.0"
Str = 'Str("")'
